version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    image: lucasbertuleza/node_app
    entrypoint: dockerize -wait tcp://db:3306 -wait tcp://nginx:80 -timeout 20s docker-entrypoint.sh
    command: node ./src/index.js
    networks:
      - node-network
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
       - db
       - nginx

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./docker/nginx
    image: lucasbertuleza/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
